### ISSUE TITLE
Drupal: Separate Drush project downloading and project enabling

### ISSUE THREAD

**Issue by wizonesolutions** [protobox/protobox#10]
Protobox currently uses the same configuration options for the contributed modules it downloads and enables. In talking with @patrickheeney on GitHub, I suggested that we separate those out, and he seemed to think it was a good idea, so I am opening an issue.

I am not picky about how the config looks — whatever works — but the end goal is something like this

``` yaml

drupal:
  - name: whatever
  # stuff
  modules:
    download:
      - ctools
      - entity
      - rules
      - fillpdf
      - ubercart
    enable:
      - ctools
      - entity_token  # entity submodule
      - fillpdf
      - fillpdf_token # fillpdf submodule
      - uc_order # in ubercart
      - uc_cart # in ubercart
      - fillpdf_ubercart_starter # in fillpdf. a bit contrived to have enabled its dependencies separately, but this is an example :D

```

Thanks!
