### ISSUE TITLE
Generated configuration with Symfony application fails

### ISSUE THREAD

**Issue by sbuzonas** [protobox/protobox#130]
`item.0.options.source` and `item.0.options.revision` will not use the fallbacks if `item.0.options` is unset.

The following configuration resolves the issue.

```
applications:
    symfony:
        -
          options: null
```
