### ISSUE TITLE
Protobox 1.0 Ideas

### ISSUE THREAD

**Issue by patrickheeney** [protobox/protobox#150]
The current version is <1.0 and more of a prototype then anything. It is bloated with the massive configuration file, required ruby gems, bloated with all the bundled code, inflexible without support for many boxes. Efforts with ansible are duplicated with ansible galaxy. 

Protobox 1.0 should be a tiny wrapper between vagrant and ansible. Right now vagrant can run ansible playbooks but doesn't have any support for easily bootstrapping applications. Ansible has ansible galaxy but no way to easily pull them in with vagrant and also is not really geared toward bootstrapping applications. So protobox should be the layer in between, thin as possible, that bootstraps any box with the required boxes.

The need for protobox / vagrant should eventually go away with things like shipyard and panamax from docker. Ideally you pull up a web gui, easily install applications as isolated docker containers. However projects like fig and docker are not easy enough on a mac due to shortcomings with shared folders. As these things are being worked in the coming years, the process should be easier to install applications.

Here is some pseudocode at how protobox 1.0 could work:

Protobox config
```
imports:
  - git: git@bitbucket.org/your/config/repo.git
    path: /data/options

vagrant:
  box: chef/ubuntu-12.04
  options: /data/options/settings.yml

playbooks:
   - git: protobox/protobox-server
     options: /data/options/server.yml

   - galaxy: foo/bar
     options: /data/options/foo.yml

   - local: /data/options/playbook
   - options: /data/options/playbookoptions
``` 

Settings.yml
```
imports:
  - /path/to/defaults.yml

memory: 2gb
```

What is demonstrated above is a simple config file that tells protobox where to find the playbooks that you wish to run. You can also use a fully configured box with everything on it and run one or two plays to bootstrap your own applications. You also specific an options parameter that get passed into the ansible playbook that was chosen. This way you can choose any playbooks from anywhere and pass in the require options in the format they require. 

Behind the scenes when you vagrant up, it parses the imports and builds the necessary config files using ruby. It talks with vagrant to configure all of the vagrant box related options and bootstraps ansible into the machine if it does not exist. 

Once the machine has ansible it now fires off our python script. It will run through the playbooks and git clone any missing ones. It will then dynamically build a playbook and passes all the options to the playbook. 

A config file for drupal and wordpress might look like this:

```
vagrant:
  box: some/php-box
  options: /data/options/settings.yml

playbooks:
   - git: wordpress/playbook
     options: /data/options/wordpress-site1.yml
   - git: wordpress/playbook
     options: /data/options/wordpress-site2.yml
   - git: wordpress/playbook
     options: /data/options/wordpress-site3.yml
   - git: drupal/playbook
     options: /data/options/drupal-site1.yml
   - git: drupal/playbook
     options: /data/options/drupal-site2.yml
```
