### ISSUE TITLE
Shared Folders

### ISSUE THREAD

**Issue by atwright147** [protobox/protobox#165]
Hi,

I am very confused about shared folders in Protobox.

I am running vagrant up from my site folder: `/Users/andy/Sites/prints.dev` (in Mac OS X Yosemite 10.10.4). 

When I ssh into the box and `cd /vagrant` then `ls` I see the contents of my host's home folder (`$HOME` aka /Users/andy/`). What do the source and target items refer to?

My .yaml file is below. What am I doing wrong?

``` yaml
protobox:
  version: 0.0.1
  build: custom
  document: 9PRX
  description: 'A custom build from getprotobox.com/share/9PRX'
  dashboard:
    install: 1
    path: /vagrant/web/protobox
vagrant:
  vm:
    box: precise64
    box_url: 'http://files.vagrantup.com/precise64.box'
    hostname: protobox
    network:
      private_network: 192.168.5.10
      forwarded_port:
        port1:
          host: ''
          guest: ''
    provider:
      virtualbox:
        modifyvm:
          name: protobox
          memory: 512
    provision:
      ansible:
        playbook: ansible/site.yml
    synced_folder:
      root:
        id: vagrant-root
        source: ./
        target: /vagrant/web/prints/
        nfs: false
        owner: vagrant
        group: www-data
        mount_options:
          - dmode=775
          - fmode=775
    usable_port_range: 2200..2250
  ssh:
    host: null
    port: null
    private_key_path: null
    public_key_path: null
    username: vagrant
    guest_port: null
    keep_alive: true
    forward_agent: false
    forward_x11: false
    shell: 'bash -l'
  vagrant:
    host: ':detect'
server:
  packages: [ ]
  ssh:
    authorized_keys: [ ]
    private_keys: [ ]
    config: [ ]
  dotfiles:
    install: 0
    repo: ''
    files: [ ]
    bash_aliases: null
apache:
  install: 1
  modules:
    - rewrite
  user: vagrant
  group: www-data
  default_vhost: false
  mpm_module: prefork
  vhosts:
    -
      name: app
      servername: app.dev
      serveraliases:
        - www.app.dev
      docroot: /vagrant/web/protobox
      port: 80
      setenv:
        - 'APP_ENV dev'
      override:
        - All
nginx:
  install: 0
  mpm_module: fpm
  vhosts:
    -
      name: app
      server_name: app.dev
      server_aliases:
        - www.app.dev
      www_root: /vagrant/web/protobox
      listen_port: 80
      index_files:
        - index.html
        - index.htm
        - index.php
      envvars:
        - 'APP_ENV dev'
php:
  install: 1
  version: '54'
  modules:
    - php5-cli
    - php5-curl
    - php5-gd
    - php5-intl
    - php5-mcrypt
  pear:
    install: 0
    modules: [ ]
  pecl:
    install: 0
    modules: [ ]
  composer:
    install: 1
  mailcatcher:
    install: 0
  phpmyadmin:
    install: 1
  xdebug:
    install: 1
    webgrind: 1
    settings:
      default_enable: '1'
      remote_autostart: '0'
      remote_connect_back: '1'
      remote_enable: '1'
      remote_handler: dbgp
      remote_port: '9000'
  xhprof:
    install: 0
    xhgui: 0
  ini:
    display_errors: On
    display_startup_errors: On
    error_reporting: '-1'
    short_open_tag: On
  timezone: UTC
hhvm:
  install: 0
  nightly: 0
  composer:
    install: 1
    use_hhvm: 1
ruby:
  install: 0
  gems: [ ]
mysql:
  install: 1
  root_password: root
  databases:
    -
      name: app
      host: localhost
      user: user
      password: user
      grant:
        - All
      sql_file: ''
mariadb:
  install: 0
  version: '5.5'
  root_password: root
  databases:
    -
      name: app
      host: localhost
      user: user
      password: user
      grant:
        - All
      sql_file: ''
rabbitmq:
  install: 0
ngrok:
  install: 0
  port: 80
newrelic:
  install: 0
  license: ''
  php: 0
  node: 0
```

**Comment by patrickheeney** [comment]
Try running `vagrant global-status` to see where the boxes are installed. It sounds like it might have been installed into your home directory rather then `/Users/andy/Sites/prints.dev`. The relevant section of the config is this:

```
    synced_folder:
      root:
        source: ./
        target: /vagrant/web/prints/
```

This basically says map the `./` current directory outside of the VM to `/vagrant/web/prints/` within the VM. If vagrant says it was installed into your home directory, then you could try the [installation](http://getprotobox.com/docs/installation) in your dev folder rather then your home directory. If that fixes it then you can delete the one from your home directory.
