### ISSUE TITLE
dot files not being copied to home directory

### ISSUE THREAD

**Issue by simshaun** [protobox/protobox#74]
I've placed a few dot files in the `data/dot` folder and ran `vagrant provision`, but the dot files aren't being copied.

The relevant config looks like this:

```
server:
  .... cut out ....
  dotfiles:
    install: 1
    files: [ ]
    bash_aliases: null
```

The Protobox website states:

> You can also add all your dotfiles (.bash_aliases, .vimrc, .gitconfig, etc), to the ./data/dot/ folder. During initial startup they will automatically be copied to the virtual machine.

I interpreted that as meaning I could drop in any dotfile I want in and they would all be copied over any time the Vagrant box is provisioned. Is that not true?
