### ISSUE TITLE
nginx `index_files` config not utilized

### ISSUE THREAD

**Issue by simshaun** [protobox/protobox#75]
It doesn't appear to be used in the nginx [default.conf.j2 template](https://github.com/protobox/protobox/blob/master/lib/ansible/roles/nginx/templates/default.conf.j2#L16).

Config:

```
nginx:
  install: 1
  vhosts:
    -
      name: app
      .... cut ....
      index_files:
        - index.html
        - index.htm
        - index.php
```

There is another issue that I'm not sure whether or not to make a new ticket for, as it regards the "index file" as well. It pertains to this line in the same template:

```
try_files $uri $uri/ /index.php?$args;
```

It would be nice if that line could be configured within the Protobox config. Some applications, such as Symfony2, utilize front controller filenames besides index.php. e.g.

```
try_files $uri $uri/ /app_dev.php?$query_string;
```
