### ISSUE TITLE
Duplicate synced folders

### ISSUE THREAD

**Issue by JacobDorman** [protobox/protobox#88]
The default synced_folder in yml downloaded from getprotobox.com is:

```
    synced_folder:
      root:
        id: vagrant-root
        source: ./
        target: /srv/www/
        nfs: false
        owner: vagrant
        group: www-data
        mount_options:
          - dmode=775
          - fmode=775
```

However vagrant already syncs ./ by default to /vagrant
Therefore on the guest `/vagrant` and `/srv/www` are duplicated. 

Is this intentional? Would this cause performance issues?
